### ISSUE TITLE
Ensure you use redux-saga@0.15.3 and not 1.x

### ISSUE THREAD

**Issue by kamranayub** [danielstern/redux-saga-cart#14]
Just wanted to create an issue for discoverability in case anyone else makes this mistake. If you follow the course instructions, you may run:

    npm install redux-saga ---save

or

    yarn add redux-saga --save

If you do this as of today, you'll install `redux-saga` 1.x

You need to ensure you install specifically `0.15.3` as shown in the course unless you want to update all the code examples to work with the new changes in 1.x (which contains breaking changes). 

    npm install redux-saga@^0.15.3 ---save

or

    yarn add redux-saga@^0.15.3 --save

An enterprising learner could do this but I wanted to call it out just in case you're stuck wondering why the code doesn't work 😄 

Thanks @danielstern!

**Comment by jvcjunior** [comment]
Thanks a lot for your help. I got stuck on some classes.
