### ISSUE TITLE
selector does not work

### ISSUE THREAD

**Issue by geomen888** [danielstern/redux-saga-cart#3]
Hi Daniel,
Need Ur advice 
first appears in module.6 last practical lesson 9.Checkout Saga
export function* checkout(){
const user = yield select(currentUserSelector)
yield put(setCheckoutPhase(QUANTITY_VERIFICATION_CHECKOUT_PHASE))
....
I'm localize prolem here in currentUserSaga.js,
unfortunatly ReactDev Tools not working at my PC 
 
import { take, put, call, apply, select} from 'redux-saga/effects'
import fetch from 'isomorphic-fetch'
import {
GET_CURRENT_USER_INFO,
setCurrentUser
} from './../actions'

import {
    currentUserSelector
} from './../selectors'

export function* currentUserSaga() {
   const { id } = yield take(GET_CURRENT_USER_INFO);
   const response = yield call(fetch, `http://localhost:8081/user/${id}`)
   const data = yield apply(response, response.json)
   console.info("ID", id)
   console.info("Data?", data)
   yield put(setCurrentUser(data))
   const user = yield select(currentUserSelector)
   console.info("Current User?", user)
}

![2018-05-14 17-51-30](https://user-images.githubusercontent.com/37697824/40005155-f0362136-579f-11e8-9433-3a61aa8f936b.png)

**Comment by danielstern** [comment]
I'm not sure I understand the question, but at first glance the screenshot looks OK. I'd say try cloning the repository and working backwards from there.
